version: "3.7"
services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: "project-test-dafidea"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_PASSWORD: ""
        volumes:
            - ./db:/var/lib/mysql
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: "project-test-dafidea"
        ports:
            - 8080:80
        volumes:
            - ./:/var/www/html
